/**
 * Client-side report export utilities.
 * Generates a formatted text file the user can download.
 * (Full PDF generation requires a server-side library; this gives
 *  immediate value without adding bundle weight.)
 */

import type { ComplianceAnalysis } from "./analysis";

export function exportReportAsText(analysis: ComplianceAnalysis): void {
  const now = new Date().toLocaleDateString("en-GB", {
    day: "2-digit", month: "long", year: "numeric",
  });

  const urgencyEmoji = { High: "🔴", Medium: "🟡", Low: "🟢" }[analysis.urgency] ?? "⚪";

  const lines = [
    `MA'AT COMPLIANCE REPORT`,
    `Generated: ${now}`,
    `${"─".repeat(48)}`,
    ``,
    `${urgencyEmoji} URGENCY: ${analysis.urgency.toUpperCase()}`,
    `⏰ DEADLINE: ${analysis.deadline}`,
    `👤 APPLIES TO: ${analysis.appliesTo}`,
    `📊 CONFIDENCE: ${analysis.confidence}`,
    ``,
    `${"─".repeat(48)}`,
    `WHAT THIS MEANS`,
    `${"─".repeat(48)}`,
    analysis.summary,
    ``,
    `${"─".repeat(48)}`,
    `NEXT STEP`,
    `${"─".repeat(48)}`,
    analysis.nextStep,
    ``,
    `${"─".repeat(48)}`,
    `ACTIONS REQUIRED`,
    `${"─".repeat(48)}`,
    ...analysis.actions.map((a, i) => `${i + 1}. ${a}`),
    ``,
    `${"─".repeat(48)}`,
    `RISKS IF IGNORED`,
    `${"─".repeat(48)}`,
    ...analysis.risks.map((r) => `• ${r}`),
    ``,
    `${"─".repeat(48)}`,
    `AMBIGUITIES & GAPS`,
    `${"─".repeat(48)}`,
    ...analysis.ambiguities.map((a) => `△ ${a}`),
    ``,
    `${"─".repeat(48)}`,
    `DISCLAIMER`,
    `${"─".repeat(48)}`,
    analysis.disclaimer,
    ``,
    `Report generated by Ma'at Compliance Simplifier`,
    `https://maat-compliance-simplifier.vercel.app`,
  ];

  const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `maat-report-${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}
